sphinxmgr: handle searchd dying early
If a searchd exits without sphinxmgr having requested it, sphinxmgr
never noticed and was always returned the name of the old socket to
clients.  That socket was either missing or had no searchd listening on
it, in which case the client failed to connect with ENOENT (2) or
ECONNREFUSED (111) respectively.  Worse, sphinxmgr also refreshed the
timestamp as a side effect, thus delaying it's own attempt to expire the
searchd, so new clients kept on getting the bogus response.  This is why
we keep seeing rashes of errors like this:

2012-10-10T05:18:16.835560-04:00 imap14 sloti14d5p4/squatter[25339]:
IOERROR: failed to connect to Sphinx: Can't connect to local MySQL
server through socket
'/mnt/ssd14/sloti14d5p4/store23/conf/socket/sphinx.brong' (2)

2012-10-10T05:20:35.682797-04:00 imap14 sloti14d5p4/squatter[25339]:
IOERROR: failed to connect to Sphinx: Can't connect to local MySQL
server through socket
'/mnt/ssd14/sloti14d5p4/store23/conf/socket/sphinx.brong' (2)

2012-10-10T05:24:17.306075-04:00 imap14 sloti14d5p4/squatter[25339]:
IOERROR: failed to connect to Sphinx: Can't connect to local MySQL
server through socket
'/mnt/ssd14/sloti14d5p4/store23/conf/socket/sphinx.brong' (2)

2012-10-10T05:30:36.557554-04:00 imap14 sloti14d5p4/squatter[25339]:
IOERROR: failed to connect to Sphinx: Can't connect to local MySQL
server through socket
'/mnt/ssd14/sloti14d5p4/store23/conf/socket/sphinx.brong' (2)

Fixed by checking for the existance of the pid file before reporting
the socket name back to the client.